"""Data models for Clinical Board system."""
from dataclasses import dataclass, field
from typing import List, Optional


BOARD_DISCLAIMER = (
    "[AI-Generated] This opinion was generated by a local multi-specialist AI system "
    "for research assistance only. It is NOT a diagnostic instrument. Final clinical "
    "judgment must be made by the attending clinician. Variant classification (ACMG/AMP) "
    "was performed by a deterministic engine and is not altered by this opinion. "
    "AI Board is powered by Google MedGemma, which is not clinical-grade."
)


@dataclass
class AgentOpinion:
    """Single domain agent's analysis opinion."""
    agent_name: str           # e.g., "Variant Pathologist"
    domain: str               # e.g., "variant_pathology"
    findings: List[dict] = field(default_factory=list)      # [{finding: str, evidence: str, confidence: str}]
    recommendations: List[str] = field(default_factory=list)
    concerns: List[str] = field(default_factory=list)
    references: List[str] = field(default_factory=list)     # PMIDs or citations
    confidence: str = "moderate"  # high/moderate/low
    raw_response: str = ""        # Original LLM response for debugging


@dataclass
class BoardOpinion:
    """Synthesized opinion from the full Clinical Board."""
    primary_diagnosis: str = ""
    primary_diagnosis_evidence: str = ""
    differential_diagnoses: List[dict] = field(default_factory=list)  # [{diagnosis, likelihood, evidence}]
    key_findings: List[str] = field(default_factory=list)
    recommendations: List[str] = field(default_factory=list)
    agent_opinions: List[AgentOpinion] = field(default_factory=list)
    agent_consensus: str = "unknown"  # unanimous/majority/split
    dissenting_opinions: List[str] = field(default_factory=list)
    follow_up: List[str] = field(default_factory=list)
    confidence: str = "moderate"
    disclaimer: str = BOARD_DISCLAIMER
    raw_response: str = ""
    # Populated by runner.py from select_board_variants() — lets render.py
    # show the audit footer without re-running the selector.
    selection_metadata: Optional[dict] = None


@dataclass
class CancerBoardOpinion:
    """Synthesized opinion from Cancer Clinical Board — treatment-focused."""
    therapeutic_headline: str = ""
    """Short (<= 120 chars) headline summarising the therapeutic stance, rendered as
    the section title. Empty when the Board Chair prompt is running against an older
    template — render.py falls back to rendering therapeutic_implications as a body
    paragraph."""
    therapeutic_implications: str = ""
    therapeutic_evidence: str = ""
    treatment_options: List[dict] = field(default_factory=list)
    actionable_findings: List[str] = field(default_factory=list)
    clinical_actions: List[str] = field(default_factory=list)
    immunotherapy_eligibility: str = ""
    agent_opinions: List[AgentOpinion] = field(default_factory=list)
    agent_consensus: str = "unknown"
    dissenting_opinions: List[str] = field(default_factory=list)
    monitoring_plan: List[str] = field(default_factory=list)
    confidence: str = "moderate"
    disclaimer: str = BOARD_DISCLAIMER
    raw_response: str = ""
    selection_metadata: Optional[dict] = None
