"""Render Clinical Board opinion as HTML for report integration."""

from scripts.clinical_board.models import BoardOpinion, CancerBoardOpinion


def _disclaimer_text(language: str) -> str:
    if language == "ko":
        return "본 소견은 Google MedGemma 모델 기반 로컬 다전문가 시스템에 의해 생성되었습니다. 최종 임상 판단은 반드시 담당 임상의가 수행해야 합니다. 변이 분류(ACMG/AMP)는 결정적 분류 엔진에 의해 수행되었으며, 본 소견은 해당 분류를 변경하지 않습니다. MedGemma는 임상 등급(clinical-grade)이 아니며, 본 출력은 진단 목적이 아닌 연구 보조 자료로만 사용되어야 합니다."
    return "This opinion was generated by a local multi-specialist system powered by Google MedGemma. Final clinical judgment must be made by the attending clinician. Variant classification (ACMG/AMP) was performed by a deterministic engine and is not altered by this opinion. MedGemma is not clinical-grade; this output is for research assistance only, not for diagnostic purposes."


def _render_header_and_disclaimer(language: str) -> list[str]:
    disclaimer_text = _disclaimer_text(language)
    return [
        """
    <style>
      details[open] > summary .board-arrow { transform: rotate(90deg); display: inline-block; transition: transform 0.2s; }
      .board-arrow { display: inline-block; transition: transform 0.2s; }
    </style>
    """,
        f"""
    <!-- AI Clinical Board Header -->
    <div class="section-header">
      <span class="section-badge" style="background:#115E59;">AI Clinical Board</span>
      <div class="section-rule" style="background:linear-gradient(90deg,#115E59,#0D9488);height:2px;"></div>
    </div>

    <!-- AI Disclaimer -->
    <div style="background:#FFFBEB;border:1px solid #FDE68A;border-radius:6px;padding:8px 14px;margin-bottom:16px;font-size:10px;color:#92400E;line-height:1.5;">
      <strong style="font-size:10px;">&#9888; AI-Generated</strong> &mdash; {disclaimer_text}
    </div>
    """,
    ]


def _render_selection_metadata_caption(selection_metadata) -> list[str]:
    """Render a small grey caption summarising the pre-analytic variant filter.

    Returns an empty list when metadata is absent so existing opinions render
    unchanged.
    """
    if not selection_metadata:
        return []
    total_input = selection_metadata.get("total_input", 0)
    selected = selection_metadata.get("selected", 0)
    criteria = selection_metadata.get("criteria_summary", "")
    truncated = selection_metadata.get("truncated", False)
    n_dropped = selection_metadata.get("n_dropped", 0)

    lines = [
        f'<div style="font-weight:600;color:#64748B;">Pre-analytic filtering: '
        f'{total_input} variants &rarr; {selected} presented to Board</div>',
    ]
    if criteria:
        lines.append(f'<div>Criteria: {criteria}</div>')
    if truncated:
        lines.append(
            f'<div>Note: selection truncated; {n_dropped} lowest-priority '
            f'variants omitted</div>'
        )
    body = "".join(lines)
    return [
        f'<div style="margin-top:12px;padding-top:8px;border-top:1px solid #E2E8F0;'
        f'font-size:9px;color:#94A3B8;line-height:1.5;">{body}</div>'
    ]


def _render_agent_opinions_section(agent_opinions) -> list[str]:
    parts: list[str] = []
    if not agent_opinions:
        return parts
    parts.append('<div style="margin-top:8px;">')
    parts.append('<div style="font-size:10px;font-weight:700;color:#94A3B8;margin-bottom:6px;">Domain Specialist Opinions</div>')
    for agent_op in agent_opinions:
        c_color = "#059669" if agent_op.confidence == "high" else "#D97706" if agent_op.confidence == "moderate" else "#DC2626"
        findings_html = ""
        for f in agent_op.findings[:3]:
            ft = f.get("finding", f) if isinstance(f, dict) else str(f)
            findings_html += f'<li style="margin-bottom:2px;">{ft}</li>'

        refs_html = ""
        if agent_op.references:
            refs_html = f'<div style="font-size:9px;color:#94A3B8;margin-top:4px;">Refs: {", ".join(agent_op.references[:3])}</div>'

        parts.append(f"""
        <details style="margin-bottom:4px;border:1px solid #E2E8F0;border-radius:4px;">
          <summary style="padding:6px 10px;background:#FAFBFD;cursor:pointer;font-size:11px;font-weight:600;color:#1E293B;list-style:none;">
            <span class="board-arrow" style="color:#0D9488;margin-right:4px;">&#9654;</span> {agent_op.agent_name}
            <span style="float:right;color:{c_color};font-size:9px;font-weight:600;">{agent_op.confidence.upper()} &middot; {len(agent_op.findings)} findings</span>
          </summary>
          <div style="padding:8px 10px;font-size:10px;color:#475569;">
            <ul style="margin:0 0 4px;padding-left:16px;line-height:1.6;">{findings_html}</ul>
            {refs_html}
          </div>
        </details>
        """)
    parts.append('</div>')
    return parts


def render_board_opinion_html(opinion, language: str = "en") -> str:
    """Render a board opinion as HTML. Dispatches on opinion type."""
    if not opinion:
        return ""
    if isinstance(opinion, CancerBoardOpinion):
        return _render_cancer_opinion(opinion, language)
    return _render_rare_disease_opinion(opinion, language)


def _render_rare_disease_opinion(opinion: BoardOpinion, language: str = "en") -> str:
    """Render BoardOpinion as an HTML section for inclusion in the report."""
    if language == "ko":
        disclaimer_text = "본 소견은 Google MedGemma 모델 기반 로컬 다전문가 시스템에 의해 생성되었습니다. 최종 임상 판단은 반드시 담당 임상의가 수행해야 합니다. 변이 분류(ACMG/AMP)는 결정적 분류 엔진에 의해 수행되었으며, 본 소견은 해당 분류를 변경하지 않습니다. MedGemma는 임상 등급(clinical-grade)이 아니며, 본 출력은 진단 목적이 아닌 연구 보조 자료로만 사용되어야 합니다."
    else:
        disclaimer_text = "This opinion was generated by a local multi-specialist system powered by Google MedGemma. Final clinical judgment must be made by the attending clinician. Variant classification (ACMG/AMP) was performed by a deterministic engine and is not altered by this opinion. MedGemma is not clinical-grade; this output is for research assistance only, not for diagnostic purposes."

    html_parts = []

    # Collapsible arrow rotation CSS
    html_parts.append("""
    <style>
      details[open] > summary .board-arrow { transform: rotate(90deg); display: inline-block; transition: transform 0.2s; }
      .board-arrow { display: inline-block; transition: transform 0.2s; }
    </style>
    """)

    # Section content (page wrapper handled by template)
    html_parts.append(f"""
    <!-- AI Clinical Board Header -->
    <div class="section-header">
      <span class="section-badge" style="background:#115E59;">AI Clinical Board</span>
      <div class="section-rule" style="background:linear-gradient(90deg,#115E59,#0D9488);height:2px;"></div>
    </div>

    <!-- AI Disclaimer -->
    <div style="background:#FFFBEB;border:1px solid #FDE68A;border-radius:6px;padding:8px 14px;margin-bottom:16px;font-size:10px;color:#92400E;line-height:1.5;">
      <strong style="font-size:10px;">&#9888; AI-Generated</strong> &mdash; {disclaimer_text}
    </div>
    """)

    # Primary Diagnosis card
    confidence_color = '#059669' if opinion.confidence == 'high' else '#D97706' if opinion.confidence == 'moderate' else '#DC2626'
    html_parts.append(f"""
    <div style="background:#F0FDFA;border:1px solid #99F6E4;border-radius:8px;padding:16px;margin-bottom:16px;">
      <div style="font-size:9px;font-weight:700;color:#115E59;text-transform:uppercase;letter-spacing:0.8px;margin-bottom:4px;">Primary Diagnosis</div>
      <div style="font-size:15px;font-weight:700;color:#1E1B4B;margin-bottom:4px;">{opinion.primary_diagnosis or 'Not determined'}</div>
      <div style="font-size:11px;color:#0F766E;line-height:1.5;">{opinion.primary_diagnosis_evidence or ''}</div>
      <div style="margin-top:8px;">
        <span style="display:inline-block;background:{confidence_color};color:#fff;border-radius:3px;padding:1px 8px;font-size:9px;font-weight:600;">Confidence: {opinion.confidence.upper()}</span>
        <span style="display:inline-block;background:#0D9488;color:#fff;border-radius:3px;padding:1px 8px;font-size:9px;font-weight:600;margin-left:4px;">Consensus: {opinion.agent_consensus}</span>
      </div>
    </div>
    """)

    # Two-column layout: Key Findings + Differential Diagnoses
    html_parts.append('<div style="display:flex;gap:16px;margin-bottom:16px;">')

    # Left: Key Findings
    html_parts.append('<div style="flex:1;">')
    html_parts.append('<div style="font-size:11px;font-weight:700;color:#1E293B;margin-bottom:6px;border-bottom:1px solid #E2E8F0;padding-bottom:4px;">Key Findings</div>')
    if opinion.key_findings:
        html_parts.append('<ul style="margin:0;padding-left:16px;font-size:10.5px;color:#334155;line-height:1.7;">')
        for f in opinion.key_findings[:6]:
            html_parts.append(f'<li>{f}</li>')
        html_parts.append('</ul>')
    else:
        html_parts.append('<p style="font-size:10.5px;color:#94A3B8;">No key findings.</p>')
    html_parts.append('</div>')

    # Right: Differential Diagnoses
    html_parts.append('<div style="flex:1;">')
    html_parts.append('<div style="font-size:11px;font-weight:700;color:#1E293B;margin-bottom:6px;border-bottom:1px solid #E2E8F0;padding-bottom:4px;">Differential Diagnoses</div>')
    if opinion.differential_diagnoses:
        html_parts.append('<table style="width:100%;border-collapse:collapse;font-size:10px;">')
        html_parts.append('<thead><tr style="background:#F8FAFC;"><th style="text-align:left;padding:4px 8px;font-weight:600;border-bottom:1px solid #E2E8F0;">Diagnosis</th><th style="text-align:center;padding:4px 6px;font-weight:600;border-bottom:1px solid #E2E8F0;width:60px;">Likelihood</th></tr></thead><tbody>')
        for dx in opinion.differential_diagnoses[:5]:
            likelihood = dx.get("likelihood", "unknown")
            lk_color = "#059669" if likelihood == "high" else "#D97706" if likelihood == "moderate" else "#9CA3AF"
            html_parts.append(f'<tr><td style="padding:4px 8px;border-bottom:1px solid #F1F5F9;font-size:10px;">{dx.get("diagnosis", "")}</td><td style="padding:4px 6px;border-bottom:1px solid #F1F5F9;text-align:center;color:{lk_color};font-weight:600;font-size:9px;">{likelihood}</td></tr>')
        html_parts.append('</tbody></table>')
    else:
        html_parts.append('<p style="font-size:10.5px;color:#94A3B8;">No differential diagnoses.</p>')
    html_parts.append('</div>')
    html_parts.append('</div>')  # end flex

    # Recommendations
    if opinion.recommendations:
        html_parts.append('<div style="margin-bottom:12px;">')
        html_parts.append('<div style="font-size:11px;font-weight:700;color:#1E293B;margin-bottom:6px;border-bottom:1px solid #E2E8F0;padding-bottom:4px;">Recommendations</div>')
        html_parts.append('<ol style="margin:0;padding-left:18px;font-size:10.5px;color:#334155;line-height:1.7;">')
        for r in opinion.recommendations[:5]:
            html_parts.append(f'<li>{r}</li>')
        html_parts.append('</ol></div>')

    # Follow-up + Dissenting (compact row)
    has_followup = bool(opinion.follow_up)
    has_dissent = bool(opinion.dissenting_opinions)
    if has_followup or has_dissent:
        html_parts.append('<div style="display:flex;gap:16px;margin-bottom:12px;">')
        if has_followup:
            html_parts.append('<div style="flex:1;">')
            html_parts.append('<div style="font-size:10px;font-weight:700;color:#64748B;margin-bottom:4px;">Follow-up</div>')
            html_parts.append('<ul style="margin:0;padding-left:16px;font-size:10px;color:#64748B;line-height:1.6;">')
            for f in opinion.follow_up[:4]:
                html_parts.append(f'<li>{f}</li>')
            html_parts.append('</ul></div>')
        if has_dissent:
            html_parts.append('<div style="flex:1;background:#FFF7ED;border:1px solid #FED7AA;border-radius:6px;padding:8px 12px;">')
            html_parts.append('<div style="font-size:10px;font-weight:700;color:#C2410C;margin-bottom:4px;">Dissenting Opinions</div>')
            html_parts.append('<ul style="margin:0;padding-left:16px;font-size:10px;color:#9A3412;line-height:1.6;">')
            for d in opinion.dissenting_opinions[:3]:
                html_parts.append(f'<li>{d}</li>')
            html_parts.append('</ul></div>')
        html_parts.append('</div>')

    # Domain Specialist Opinions (collapsible, compact)
    if opinion.agent_opinions:
        html_parts.append('<div style="margin-top:8px;">')
        html_parts.append('<div style="font-size:10px;font-weight:700;color:#94A3B8;margin-bottom:6px;">Domain Specialist Opinions</div>')
        for agent_op in opinion.agent_opinions:
            c_color = "#059669" if agent_op.confidence == "high" else "#D97706" if agent_op.confidence == "moderate" else "#DC2626"
            findings_html = ""
            for f in agent_op.findings[:3]:
                ft = f.get("finding", f) if isinstance(f, dict) else str(f)
                findings_html += f'<li style="margin-bottom:2px;">{ft}</li>'

            refs_html = ""
            if agent_op.references:
                refs_html = f'<div style="font-size:9px;color:#94A3B8;margin-top:4px;">Refs: {", ".join(agent_op.references[:3])}</div>'

            html_parts.append(f"""
            <details style="margin-bottom:4px;border:1px solid #E2E8F0;border-radius:4px;">
              <summary style="padding:6px 10px;background:#FAFBFD;cursor:pointer;font-size:11px;font-weight:600;color:#1E293B;list-style:none;">
                <span class="board-arrow" style="color:#0D9488;margin-right:4px;">&#9654;</span> {agent_op.agent_name}
                <span style="float:right;color:{c_color};font-size:9px;font-weight:600;">{agent_op.confidence.upper()} &middot; {len(agent_op.findings)} findings</span>
              </summary>
              <div style="padding:8px 10px;font-size:10px;color:#475569;">
                <ul style="margin:0 0 4px;padding-left:16px;line-height:1.6;">{findings_html}</ul>
                {refs_html}
              </div>
            </details>
            """)
        html_parts.append('</div>')

    # Pre-analytic filtering caption (footer)
    html_parts.extend(_render_selection_metadata_caption(opinion.selection_metadata))

    # No closing page div — template handles page wrapper

    return "\n".join(html_parts)


def _render_cancer_opinion(opinion: CancerBoardOpinion, language: str = "en") -> str:
    """Render CancerBoardOpinion as a treatment-focused HTML section."""
    html_parts: list[str] = []
    html_parts.extend(_render_header_and_disclaimer(language))

    confidence_color = (
        '#059669' if opinion.confidence == 'high'
        else '#D97706' if opinion.confidence == 'moderate'
        else '#DC2626'
    )

    # Therapeutic Implications card (replaces Primary Diagnosis)
    html_parts.append(f"""
    <div style="background:#F0FDFA;border:1px solid #99F6E4;border-radius:8px;padding:16px;margin-bottom:16px;">
      <div style="font-size:9px;font-weight:700;color:#115E59;text-transform:uppercase;letter-spacing:0.8px;margin-bottom:4px;">Therapeutic Implications</div>
      <div style="font-size:15px;font-weight:700;color:#1E1B4B;margin-bottom:4px;">{opinion.therapeutic_implications or 'Not determined'}</div>
      <div style="font-size:11px;color:#0F766E;line-height:1.5;">{opinion.therapeutic_evidence or ''}</div>
      <div style="margin-top:8px;">
        <span style="display:inline-block;background:{confidence_color};color:#fff;border-radius:3px;padding:1px 8px;font-size:9px;font-weight:600;">Confidence: {opinion.confidence.upper()}</span>
        <span style="display:inline-block;background:#0D9488;color:#fff;border-radius:3px;padding:1px 8px;font-size:9px;font-weight:600;margin-left:4px;">Consensus: {opinion.agent_consensus}</span>
      </div>
    </div>
    """)

    # Treatment Options table
    html_parts.append('<div style="margin-bottom:16px;">')
    html_parts.append('<div style="font-size:11px;font-weight:700;color:#1E293B;margin-bottom:6px;border-bottom:1px solid #E2E8F0;padding-bottom:4px;">Treatment Options</div>')
    if opinion.treatment_options:
        html_parts.append('<table style="width:100%;border-collapse:collapse;font-size:10px;">')
        html_parts.append(
            '<thead><tr style="background:#F8FAFC;">'
            '<th style="text-align:left;padding:4px 8px;font-weight:600;border-bottom:1px solid #E2E8F0;">Drug</th>'
            '<th style="text-align:center;padding:4px 6px;font-weight:600;border-bottom:1px solid #E2E8F0;width:80px;">Evidence</th>'
            '<th style="text-align:left;padding:4px 8px;font-weight:600;border-bottom:1px solid #E2E8F0;">Resistance Notes</th>'
            '</tr></thead><tbody>'
        )
        for opt in opinion.treatment_options[:8]:
            drug = opt.get("drug", "")
            level = opt.get("evidence_level", "")
            resistance = opt.get("resistance_notes", "")
            lv_color = "#059669" if level in ("A", "1") else "#D97706" if level in ("B", "2") else "#9CA3AF"
            html_parts.append(
                f'<tr>'
                f'<td style="padding:4px 8px;border-bottom:1px solid #F1F5F9;font-weight:600;">{drug}</td>'
                f'<td style="padding:4px 6px;border-bottom:1px solid #F1F5F9;text-align:center;color:{lv_color};font-weight:600;font-size:9px;">{level}</td>'
                f'<td style="padding:4px 8px;border-bottom:1px solid #F1F5F9;color:#64748B;word-break:break-word;">{resistance}</td>'
                f'</tr>'
            )
        html_parts.append('</tbody></table>')
    else:
        html_parts.append('<p style="font-size:10.5px;color:#94A3B8;">No treatment options identified.</p>')
    html_parts.append('</div>')

    # Immunotherapy Eligibility badge
    if opinion.immunotherapy_eligibility:
        ie = opinion.immunotherapy_eligibility
        ie_lower = ie.lower()
        ie_color = "#059669" if ("eligible" in ie_lower and "not" not in ie_lower) or "high" in ie_lower else "#D97706"
        html_parts.append(
            f'<div style="margin-bottom:12px;">'
            f'<span style="display:inline-block;background:{ie_color};color:#fff;border-radius:4px;padding:3px 10px;font-size:10px;font-weight:700;">'
            f'Immunotherapy: {ie}</span></div>'
        )

    # Actionable Findings + Clinical Actions (two-column)
    has_actionable = bool(opinion.actionable_findings)
    has_actions = bool(opinion.clinical_actions)
    if has_actionable or has_actions:
        html_parts.append('<div style="display:flex;gap:16px;margin-bottom:12px;">')
        if has_actionable:
            html_parts.append('<div style="flex:1;">')
            html_parts.append('<div style="font-size:11px;font-weight:700;color:#1E293B;margin-bottom:6px;border-bottom:1px solid #E2E8F0;padding-bottom:4px;">Actionable Findings</div>')
            html_parts.append('<ul style="margin:0;padding-left:16px;font-size:10.5px;color:#334155;line-height:1.7;">')
            for f in opinion.actionable_findings[:6]:
                html_parts.append(f'<li>{f}</li>')
            html_parts.append('</ul></div>')
        if has_actions:
            html_parts.append('<div style="flex:1;">')
            html_parts.append('<div style="font-size:11px;font-weight:700;color:#1E293B;margin-bottom:6px;border-bottom:1px solid #E2E8F0;padding-bottom:4px;">Clinical Actions</div>')
            html_parts.append('<ol style="margin:0;padding-left:18px;font-size:10.5px;color:#334155;line-height:1.7;">')
            for a in opinion.clinical_actions[:6]:
                html_parts.append(f'<li>{a}</li>')
            html_parts.append('</ol></div>')
        html_parts.append('</div>')

    # Monitoring Plan + Dissenting Opinions
    has_monitoring = bool(opinion.monitoring_plan)
    has_dissent = bool(opinion.dissenting_opinions)
    if has_monitoring or has_dissent:
        html_parts.append('<div style="display:flex;gap:16px;margin-bottom:12px;">')
        if has_monitoring:
            html_parts.append('<div style="flex:1;">')
            html_parts.append('<div style="font-size:10px;font-weight:700;color:#64748B;margin-bottom:4px;">Monitoring Plan</div>')
            html_parts.append('<ul style="margin:0;padding-left:16px;font-size:10px;color:#64748B;line-height:1.6;">')
            for m in opinion.monitoring_plan[:4]:
                html_parts.append(f'<li>{m}</li>')
            html_parts.append('</ul></div>')
        if has_dissent:
            html_parts.append('<div style="flex:1;background:#FFF7ED;border:1px solid #FED7AA;border-radius:6px;padding:8px 12px;">')
            html_parts.append('<div style="font-size:10px;font-weight:700;color:#C2410C;margin-bottom:4px;">Dissenting Opinions</div>')
            html_parts.append('<ul style="margin:0;padding-left:16px;font-size:10px;color:#9A3412;line-height:1.6;">')
            for d in opinion.dissenting_opinions[:3]:
                html_parts.append(f'<li>{d}</li>')
            html_parts.append('</ul></div>')
        html_parts.append('</div>')

    # Domain Specialist Opinions
    html_parts.extend(_render_agent_opinions_section(opinion.agent_opinions))

    # Pre-analytic filtering caption (footer)
    html_parts.extend(_render_selection_metadata_caption(opinion.selection_metadata))

    return "\n".join(html_parts)
